### PR TITLE
Background threads don't report exceptions (close #394)

### LINKED ISSUE #394: Background threads don't report exceptions
When a background threads hit an exception it just fails silently. Nothing is reported to the app or logged anywhere.

Those exception has to be logged in the console and handled by the diagnostic feature.

### PR DESCRIPTION
**Pull request by AlexBenny**
The background threads weren't able to report exceptions correctly. They failed silently and lot of the operations done by the Android tracker happen in background threads.
We need to report those issues in the logs, and eventually with the diagnostic feature, in order to spot in advance anything suspicious in the tracker behaviour.

### CODE REVIEW

File: snowplow-tracker/src/androidTest/java/com/snowplowanalytics/snowplow/tracker/ExecutorTest.java [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+            synchronized (expectation) {
+                expectation.notify();
+            }
+        });
+        synchronized (expectation) {
+            expectation.wait(10000);
+        }
+        assertTrue(exceptionRaised.get());
+    }
+}
```
Comment (paulboocock) [inline snowplow-tracker/src/androidTest/java/com/snowplowanalytics/snowplow/tracker/ExecutorTest.java:34]: Missing new line
