### PR TITLE
Fix wrong screen entity info assigned for screen end event and in case events are tracked right before screen view (close #673)

### LINKED ISSUE #673: Fix wrong screen entity info assigned for screen end event and in case events are tracked in parallel
Due to a bug in how the screen state is updated in the tracker, the screen end event is assigned the wrong information – instead of referring to the previous screen name and ID, it contains information of the subsequent screen.

This bug is not only limited to screen end events but may also appear in case an event is tracked right before a screen view event – the event will be assigned the next screen view instead of the one used when it was tracked.

### PR DESCRIPTION
**Pull request by matus-tomlein**
Issue #673 

Due to a bug in how the screen state is updated in the tracker, the screen end event is assigned the wrong information – instead of referring to the previous screen name and ID, it contains information of the subsequent screen.

This bug is not only limited to screen end events but may also appear in case an event is tracked right before a screen view event – the event will be assigned the next screen view instead of the one used when it was tracked.

### CODE REVIEW

File: snowplow-tracker/src/androidTest/java/com/snowplowanalytics/snowplow/screen/ScreenViewAutotrackingTest.kt [hunk 1]
```diff
@@ -69,9 +61,10 @@ class ScreenViewAutotrackingTest {
         NotificationCenter.postNotification("SnowplowScreenView", mapOf(
             "event" to ScreenView(name = "Screen2").activityClassName("Screen2")
         ))
-        Thread.sleep(200)
+        Thread.sleep(2000)
 
-        Assert.assertEquals(2, numberOfScreenViews)
+        val numberOfScreenViews = eventSink.trackedEvents.filter { it.schema == TrackerConstants.SCHEMA_SCREEN_VIEW }
```
Comment (mscwilson) [inline snowplow-tracker/src/androidTest/java/com/snowplowanalytics/snowplow/screen/ScreenViewAutotrackingTest.kt:66]: nit: strange name for a list, I was expecting an int

File: snowplow-tracker/src/androidTest/java/com/snowplowanalytics/snowplow/screenviews/ScreenSummaryStateMachineTest.kt [hunk 2]
```diff
@@ -94,9 +94,14 @@ class ScreenSummaryStateMachineTest {
...
         Assert.assertEquals(3, events.size)
 
-        val screenSummary = getScreenSummary(events.find { it.schema == TrackerConstants.SCHEMA_SCREEN_END })
+        val screenEnd = events.find { it.schema == TrackerConstants.SCHEMA_SCREEN_END }
+        val screenSummary = getScreenSummary(screenEnd)
         Assert.assertEquals(10.0, screenSummary?.get("foreground_sec"))
         Assert.assertEquals(0.0, screenSummary?.get("background_sec"))
+
+        // should have the screen name of the first screen view
+        val screenEndScreen = screenEnd?.entities?.find { it.map["schema"] == TrackerConstants.SCHEMA_SCREEN }
```
Comment (mscwilson) [inline snowplow-tracker/src/androidTest/java/com/snowplowanalytics/snowplow/screenviews/ScreenSummaryStateMachineTest.kt:103]: I've read the word "screen" so much it doesn't look like a real word anymore

**Review by mscwilson — APPROVED** [review]
LGTM!

File: snowplow-tracker/src/androidTest/java/com/snowplowanalytics/snowplow/screen/ScreenViewAutotrackingTest.kt (hunk 1 above)
Comment (matus-tomlein) [reply snowplow-tracker/src/androidTest/java/com/snowplowanalytics/snowplow/screen/ScreenViewAutotrackingTest.kt]: Good catch, fixed now.

File: snowplow-tracker/src/main/java/com/snowplowanalytics/core/tracker/Tracker.kt [hunk 3]
```diff
@@ -333,8 +328,9 @@ class Tracker(
         override fun apply(data: Map<String, Any>) {
             if (screenViewAutotracking) {
                 val event = data["event"] as? ScreenView?
-                event?.let { event ->
-                    getScreenState()?.let { state ->
+                if (event != null) {
```
[the remark this answers is not in the document]
Comment (matus-tomlein) [reply snowplow-tracker/src/main/java/com/snowplowanalytics/core/tracker/Tracker.kt:331]: It had a slightly different behaviour which I think was unintended – the `?: track(event)` part could be executed even in case the previous `let` block was evaluated but returned `null`. I think this if-else better reflects what should happen and is a bit more clear.
