### PR TITLE
Report logs to the app (close #407)

### LINKED ISSUE #407: Report logs to the app
It's the Android counterpart of the [iOS issue #534](https://github.com/snowplow/snowplow-objc-tracker/issues/534).
The diagnostic feature lets the tracker to report some errors to the collector in order to be tracked along with the regular events (only if the diagnostic feature is enabled - disabled by default). With this enhancement we allow the app to get the tracker logs (Error, Debug, Verbose). This can be helpful during debugging and for inspecting issues during instrumentation of the tracker or troubleshooting of unexpected behaviours.

### PR DESCRIPTION
**Pull request by AlexBenny**
Allow the app to receive logs (Error, Debug, Verbose) from the tracker.

Here draft of documentation for the [`Tracker diagnostics` section](https://docs.snowplowanalytics.com/docs/collecting-data/collecting-from-own-applications/android-tracker/android-1-5-0/#tracker-diagnostics) that will be changed in `Troubleshooting` section:

---

Troubleshooting
---

The tracker is constantly tested with different platforms and versions but there are rare situations where an error can be generated. The tracker will manage the situation to avoid crashes of the app and assuring that the events are not lost.

However, it can be useful to observe logs and errors from the tracker in order to narrow down a possible issue due to a mistake in the instrumentation of the tracker in the app or other unexpected behaviours.

We let the developer to have a full visibility of the tracker logs. *Please, take care to avoid sharing of sensible information through the logs when in production environment*.

At the tracker configuration you can decide which log level you want to filter logs:

```
TrackerBuilder trackerBuilder =
    new TrackerBuilder(emitter, namespace, appId, appContext)
        ...
        .level(LogLevel.VERBOSE)
        ...
        .build();
Tracker.init(trackerBuilder);
```

There are four levels of logging: off (log disabled), error, debug, verbose.

In this way the logs will be sent to the system logs. Usually visible through Logcat, which is a system log module. It contains all the device errors and warnings.

It's also possible to handle the tracker logs directly in the app for troubleshooting purposes. You need to implement the interface `LoggerDelegate` where you will receive all the log messages based on the log level selected.
In the tracker configuration you have to set the log level and register the logger delegate passing the reference of class instance that implement the LoggerDelegate interface.

```
public class MyApp implements LoggerDelegate {

    ...

    private void setupMyTracker() {
        ...
        TrackerBuilder trackerBuilder =
            new TrackerBuilder(emitter, namespace, appId, appContext)
                .level(LogLevel.ERROR)
                .loggerDelegate(this)
                ...
                .build();
        Tracker.init(trackerBuilder);
    }

    ...

    // - LoggerDelegate methods

    @Override
    public void error(String tag, String msg) { ... }

    @Override
    public void debug(String tag, String msg) { ... }

    @Override
    public void verbose(String tag, String msg) { ... }
}
```

A third option, suitable for issues happening in a production environment, is the diagnostic tracking.
Errors happening in the tracker can be reported to the collector as `diagnostic_error` events.
If you enable the diagnostic feature the log level will be automatically set to error level.

To activate this feature you only need to enable `trackerDiagnostic`:

```
TrackerBuilder trackerBuilder =
    new TrackerBuilder(emitter, namespace, appId, appContext)
        .trackerDiagnostic(true)
        ...
        .build();
Tracker.init(trackerBuilder);
```

### CODE REVIEW

**Comment by AlexBenny** [comment]
@paulboocock - it's not urgent. I've also rewritten the doc related to Diagnostic (in the description of this PR) could you please give a look at that along with this PR? thanks!

**Comment by paulboocock** [comment]
Updated the grammar in a couple of places:

> Allow the app to receive logs (Error, Debug, Verbose) from the tracker.
> 
> Here draft of documentation for the [`Tracker diagnostics` section](https://docs.snowplowanalytics.com/docs/collecting-data/collecting-from-own-applications/android-tracker/android-1-5-0/#tracker-diagnostics) that will be changed in `Troubleshooting` section:
> ## Troubleshooting
> 
> The tracker is tested with different platforms and versions but there are rare situations where an error can be generated. The tracker will manage these errors to avoid crashes of the app and assure that the events are not lost.
> 
> However, it can be useful to observe logs and errors from the tracker in order to narrow down a possible issue. Perhaps due to a mistake in the instrumentation of the tracker in the app or other unexpected behaviour.
> 
> We let the developer to have a full visibility of the tracker logs. _Please, take care to avoid sharing of sensitive information through the logs when in production environment_.
> 
> At tracker configuration you can decide which log level you want to filter logs to:
> 
> ```
> TrackerBuilder trackerBuilder =
>     new TrackerBuilder(emitter, namespace, appId, appContext)
>         ...
>         .level(LogLevel.VERBOSE)
>         ...
>         .build();
> Tracker.init(trackerBuilder);
> ```
> 
> There are four levels of logging: off (log disabled), error, debug, verbose.
> 
> In the example above, all logs will be sent to the system logs. Usually visible through Logcat, which is a system log module. It contains all the device errors and warnings.
> 
> It's also possible to handle the tracker logs directly in the app for troubleshooting purposes. You need to implement the interface `LoggerDelegate` where you will receive all the log messages based on the log level selected.
> In the tracker configuration you have to set the log level and register the logger delegate. Pass a reference of a class instance that implements the LoggerDelegate interface.
> 
> ```
> public class MyApp implements LoggerDelegate {
> 
>     ...
> 
>     private void setupMyTracker() {
>         ...
>         TrackerBuilder trackerBuilder =
>             new TrackerBuilder(emitter, namespace, appId, appContext)
>                 .level(LogLevel.ERROR)
>                 .loggerDelegate(this)
>                 ...
>                 .build();
>         Tracker.init(trackerBuilder);
>     }
> 
>     ...
> 
>     // - LoggerDelegate methods
> 
>     @Override
>     public void error(String tag, String msg) { ... }
> 
>     @Override
>     public void debug(String tag, String msg) { ... }
> 
>     @Override
>     public void verbose(String tag, String msg) { ... }
> }
> ```
> 
> A third option, suitable for issues happening in a production environment, is diagnostic tracking.
> Errors happening in the tracker can be reported to the collector as `diagnostic_error` events.
> If you enable the diagnostic feature the log level will be automatically set to error level.
> 
> To activate this feature you only need to enable `trackerDiagnostic`:
> 
> ```
> TrackerBuilder trackerBuilder =
>     new TrackerBuilder(emitter, namespace, appId, appContext)
>         .trackerDiagnostic(true)
>         ...
>         .build();
> Tracker.init(trackerBuilder);
> ```

File: snowplow-tracker/src/main/java/com/snowplowanalytics/snowplow/tracker/utils/Logger.java [hunk 1]
```diff
@@ -62,7 +93,13 @@ public static void track(String tag, String msg, Object... args) {
      */
     public static void e(String tag, String msg, Object... args) {
         if (level >= 1) {
-            Log.e(getTag(tag), getMessage(msg, args));
+            String source = getTag(tag);
+            String message = getMessage(msg, args);
+            if (delegate != null) {
```
Comment (paulboocock) [inline snowplow-tracker/src/main/java/com/snowplowanalytics/snowplow/tracker/utils/Logger.java:98]: Would it be worth creating an internal `LoggerDelegate`, and using this when constructing the `Tracker`? This internal delegate could call the `Log...` methods removing the need for this `if`. Makes the code more polymorphic.
