### PR TITLE
Log an error when recreating tracker after being removed (close #548)

### LINKED ISSUE #548: Log an error when recreating tracker after being removed
Currently, when one removes a tracker using `Snowplow.removeTracker(tracker)` (this closes the tracker) and then calls for instance `tracker.getNamespace()`, the tracker is reinitialized and starts tracking again (e.g., subscribes to automatic screen view tracking). This is unexpected behaviour as the user didn't request the tracker to be reinitialized.

The problem is in the implementation of the `getTracker()` method in `ServiceProvider` (and `TrackerController` in consequence) which calls `makeTracker()` in case the tracker reference is null to initialize it. We should not make a new tracker if it was previously removed.

### PR DESCRIPTION
**Pull request by matus-tomlein**
Issue #548 

The problem that we are dealing with here is that users got confusing behaviour after having code that did something similar to this:

```java
TrackerController tracker = Snowplow.createTracker(...);
Snowplow.removeTracker(tracker);
System.out.println("Tracker removed: " + tracker.getNamespace());
```

In this case the tracker was removed on the second line but it was reinitialized on the third line, which is not obvious based on the snippet. Reinitializing the tracker also means that various autotracking features may be reactivated and unexpected events tracked.

I would like to prevent this behaviour and just return NULL from the `getNamespace()` and other functions from the `TrackerController` but I realized that this would be a breaking change. We would need to change the signature of the `TrackerController` functions.

So in order to prevent making the breaking change, this PR:

1. Logs an error when a tracker that was previously removed is accessed. This should make it easier for users to debug the weird behaviour.
2. Renames some of the internal functions to make clear that they are not just getters but can also change the objects (e.g., `getTracker()` -> `getOrMakeTracker()`).

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://docs.snowplowanalytics.com/docs/contributing/contributor-license-agreement/ to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

File: snowplow-tracker/src/main/java/com/snowplowanalytics/snowplow/internal/tracker/ServiceProvider.java [hunk 1]
```diff
@@ -233,79 +232,95 @@ private void initializeConfigurationUpdates() {
     // Getters
 
     @NonNull
-    public Subject getSubject() {
+    @Override
+    public Subject getOrMakeSubject() {
```
Comment (AlexBenny) [inline snowplow-tracker/src/main/java/com/snowplowanalytics/snowplow/internal/tracker/ServiceProvider.java:236]: 👍 👍

File: snowplow-tracker/src/main/java/com/snowplowanalytics/snowplow/internal/tracker/ServiceProvider.java [hunk 2]
```diff
@@ -233,79 +232,95 @@ private void initializeConfigurationUpdates() {
...
         }
         return emitter;
     }
 
     @NonNull
-    public Tracker getTracker() {
+    @Override
+    public Boolean isTrackerInitialized() {
+        return tracker != null;
+    }
```
Comment (AlexBenny) [inline snowplow-tracker/src/main/java/com/snowplowanalytics/snowplow/internal/tracker/ServiceProvider.java:256]: Same thought I already added on iOS Tracker.
Rethinking to this, maybe we could call this method "isAlive" or "isActive" or in negative form "isInvalidated", related to the fact that it's the ServiceProvider that should be dead but it's still used.
Just a thought btw.

**Review by AlexBenny — APPROVED** [review]
LGTM! 👍 👍  Same thought already reported for iOS Tracker.
